#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.


. "$LIB_DIR/common.sh"
. "$OUT_DIR/load-core-addr-temp"

auction_throttler_deployer=$(dappCreate h2o-governance-actions DeployCollateralAuctionThottler)

# https://github.com/stablecoin-research/h2o-governance-actions/blob/master/src/DeployCollateralAuctionThottler.sol#L20
calldata="$(seth calldata "execute(address,address,address)" "$GEB_SAFE_ENGINE" "$GEB_LIQUIDATION_ENGINE" "$GEB_STABILITY_FEE_TREASURY")"

export SETH_ASYNC=yes
deploy_tx="$(sethSend "$PROXY_DEPLOYER" 'execute(address,bytes memory)' "$auction_throttler_deployer" "$calldata")"
echo "$deploy_tx"
export SETH_ASYNC=no

tx_topics="$(seth receipt "$deploy_tx" logs | jq -c '.| .[] | select(.topics[0] == "0xfe49061ea17152b4588a19e9bcd72c49acaac19e896c10fd6f2ac7e20b94fc78") | .topics')"
COLLATERAL_AUCTION_THROTTLER="$(seth --to-hex "$(seth --to-dec "$(echo $tx_topics | jq -r ".[1]")")")"

cat > "$OUT_DIR/load-auction-throttler-addr-temp" <<EOF
#!/bin/bash
export COLLATERAL_AUCTION_THROTTLER=$COLLATERAL_AUCTION_THROTTLER
EOF
