#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

. "$OUT_DIR/load-core-addr-temp"
 

### MISSING PARAMETERS IN CONFIG FILE
# https://github.com/stablecoin-research/h2o-debt-floor-adjuster.git

cat > "$OUT_DIR/load-debt-floor-adjuster-addr-temp" <<EOF
#!/bin/bash
export COLLATERAL_AUCTION_THROTTLER=$COLLATERAL_AUCTION_THROTTLER
EOF
