#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

# Get config variables
CONFIG_FILE="$OUT_DIR/config.json"
# Get addresses
loadAddresses

log "SET SAFE ENGINE PARAMS:"

global_debt_ceiling="$(readValue ".safe_engine.global_debt_ceiling" "$CONFIG_FILE" "int256")"
sethSend "$(eval echo "\$GEB_SAFE_ENGINE")" 'modifyParameters(bytes32,uint256)' "$(seth --to-bytes32 "$(seth --from-ascii "globalDebtCeiling")")" "$global_debt_ceiling"

safe_debt_ceiling="$(readValue ".safe_engine.safe_debt_ceiling" "$CONFIG_FILE")"
sethSend "$(eval echo "\$GEB_SAFE_ENGINE")" 'modifyParameters(bytes32,uint256)' "$(seth --to-bytes32 "$(seth --from-ascii "safeDebtCeiling")")" "$safe_debt_ceiling"
