#!/usr/bin/env bash

#  Copyright (C) 2019-2021 Maker Ecosystem Growth Holdings, INC.

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.

#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# shellcheck source=lib/common.sh
. "$LIB_DIR/common.sh"

. "$OUT_DIR/load-core-addr-temp"

base_caller_reward=$(readValue ".single_ceiling_setter.base_caller_reward | values" "$CONFIG_FILE")
max_caller_reward=$(readValue ".single_ceiling_setter.max_caller_reward | values" "$CONFIG_FILE")

reward_increase=$(readValue ".single_ceiling_setter.reward_increase | values" "$CONFIG_FILE")
update_delay=$(readValue ".single_ceiling_setter.update_delay | values" "$CONFIG_FILE")

ceiling_percentage_change=$(readValue ".single_ceiling_setter.ceiling_percentage_change | values" "$CONFIG_FILE")

max_collateral_ceiling=$(readValue ".single_ceiling_setter.max_collateral_ceiling | values" "$CONFIG_FILE" "int256")

min_collateral_ceiling=$(readValue ".single_ceiling_setter.min_collateral_ceiling | values" "$CONFIG_FILE")

tokens=$(jq -r ".tokens | keys_unsorted[]" "$CONFIG_FILE")
collateral_token="${tokens[0]}"
collateral_types=$(jq -r ".tokens.${collateral_token}.collateral_types | keys_unsorted[]" "$CONFIG_FILE")
collateral_token_type="${collateral_types[0]}"
collateral_type_name=$(seth --to-bytes32 "$(seth --from-ascii "${collateral_token}-${collateral_token_type}")")

GEB_SINGLE_CEILING_SETTER="$(dappCreate geb-debt-ceiling-setter SingleSpotDebtCeilingSetter \
    "$GEB_SAFE_ENGINE" \
    "$GEB_ORACLE_RELAYER" \
    "$GEB_STABILITY_FEE_TREASURY" \
    "$collateral_type_name" \
    "$base_caller_reward" \
    "$max_caller_reward" \
    "$reward_increase" \
    "$update_delay" \
    "$ceiling_percentage_change" \
    "$max_collateral_ceiling" \
    "$min_collateral_ceiling" \
    )"

# Set up authorization
sethSend "$GEB_SAFE_ENGINE" "addAuthorization(address)" "$GEB_SINGLE_CEILING_SETTER"

cat > "$OUT_DIR/load-debt-ceiling-setter-addr-temp" <<EOF
#!/bin/bash
export GEB_SINGLE_CEILING_SETTER=$GEB_SINGLE_CEILING_SETTER
EOF
